platform :ios ,'8.0'
target 'RealEstateTycoonProject' do
pod 'FMDB','~>2.6.2'
pod 'SDWebImage','~>3.8.2'
pod 'AFNetworking','~>3.1.0'
pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'YYModel','~>1.0.4'
end

